language: python
python:
    - "2.7"
    - "3.5"
    - "3.7"
install:
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"
    - "pip install coveralls"
script: "python setup.py test"
after_success: "coveralls"
